name: Generate formulae.brew.sh data.

on: [push]

jobs:
  generate:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: Homebrew/actions/git-ssh@master
        with:
          git_user: BrewTestBot
          git_email: homebrew-test-bot@lists.sfconservancy.org
          key: ${{ secrets.FORMULAE_DEPLOY_KEY }}
      - run: |
          brew update-reset "$(brew --repository)"
          brew tap "$GITHUB_REPOSITORY"
          brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"

          export PATH="$(brew --repo)/Library/Homebrew/vendor/portable-ruby/current/bin:$PATH"

          brew install --build-from-source Formula/awscurl.rb
        env:
          ANALYTICS_JSON_KEY: ${{ secrets.ANALYTICS_JSON_KEY }}
